/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FormData {
  'name' : string,
  'email' : string,
  'message' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cleaningComplete' : null } |
  { 'inspectionComplete' : null } |
  { 'finalTouches' : null } |
  { 'inPress' : null } |
  { 'packageReceived' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface RestorationStep {
  'completed' : boolean,
  'description' : string,
  'timestamp' : Time,
}
export interface Ticket {
  'completed' : boolean,
  'formData' : FormData,
  'category' : string,
}
export type Time = bigint;
export interface TrackingStateView {
  'shipped' : boolean,
  'trackingCode' : string,
  'arrived' : boolean,
  'restorationLevel' : string,
  'steps' : Array<RestorationStep>,
  'shippingTimestamp' : [] | [Time],
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminId' : ActorMethod<[Principal], undefined>,
  'addCategories' : ActorMethod<[string, Array<string>], undefined>,
  'addCategory' : ActorMethod<[string, string], undefined>,
  'addRestorationStep' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkTrackingNumberStatus' : ActorMethod<[string], OrderStatus>,
  'completeRestorationStep' : ActorMethod<[string, bigint], undefined>,
  'createOrder' : ActorMethod<[string], OrderStatus>,
  'createTrackingState' : ActorMethod<[string, string], undefined>,
  'examineTrackingNumbers' : ActorMethod<[], Array<[string, OrderStatus]>>,
  'getAdminIds' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInitializationStatus' : ActorMethod<
    [],
    {
      'callerRole' : string,
      'isInitialized' : boolean,
      'callerIsAdmin' : boolean,
    }
  >,
  'getTrackingNumbers' : ActorMethod<[], Array<[string, OrderStatus]>>,
  'getTrackingState' : ActorMethod<[string], [] | [TrackingStateView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTicketCompleted' : ActorMethod<[string], boolean>,
  'listAllTickets' : ActorMethod<[], Array<[string, Ticket]>>,
  'markPackageArrived' : ActorMethod<[string], undefined>,
  'markShipped' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updateTicketStatus' : ActorMethod<[string, boolean], undefined>,
  'updateTrackingNumberStatus' : ActorMethod<
    [string, OrderStatus],
    OrderStatus
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];