/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'addCategories' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isTicketCompleted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTicketStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'addCategories' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isTicketCompleted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTicketStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };