/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const RestorationStep = IDL.Record({
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const TrackingStateView = IDL.Record({
  'shipped' : IDL.Bool,
  'trackingCode' : IDL.Text,
  'arrived' : IDL.Bool,
  'restorationLevel' : IDL.Text,
  'steps' : IDL.Vec(RestorationStep),
  'shippingTimestamp' : IDL.Opt(Time),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategories' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addRestorationStep' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrap' : IDL.Func([], [], []),
  'checkTrackingNumberStatus' : IDL.Func([IDL.Text], [OrderStatus], ['query']),
  'completeRestorationStep' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createOrder' : IDL.Func([IDL.Text], [OrderStatus], []),
  'createTrackingState' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'examineTrackingNumbers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, OrderStatus))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTrackingNumbers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, OrderStatus))],
      ['query'],
    ),
  'getTrackingState' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TrackingStateView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTicketCompleted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'markPackageArrived' : IDL.Func([IDL.Text], [], []),
  'markShipped' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTicketStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateTrackingNumberStatus' : IDL.Func(
      [IDL.Text, OrderStatus],
      [OrderStatus],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Time = IDL.Int;
  const RestorationStep = IDL.Record({
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const TrackingStateView = IDL.Record({
    'shipped' : IDL.Bool,
    'trackingCode' : IDL.Text,
    'arrived' : IDL.Bool,
    'restorationLevel' : IDL.Text,
    'steps' : IDL.Vec(RestorationStep),
    'shippingTimestamp' : IDL.Opt(Time),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategories' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addRestorationStep' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrap' : IDL.Func([], [], []),
    'checkTrackingNumberStatus' : IDL.Func(
        [IDL.Text],
        [OrderStatus],
        ['query'],
      ),
    'completeRestorationStep' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createOrder' : IDL.Func([IDL.Text], [OrderStatus], []),
    'createTrackingState' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'examineTrackingNumbers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, OrderStatus))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTrackingNumbers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, OrderStatus))],
        ['query'],
      ),
    'getTrackingState' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrackingStateView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTicketCompleted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'markPackageArrived' : IDL.Func([IDL.Text], [], []),
    'markShipped' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTicketStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateTrackingNumberStatus' : IDL.Func(
        [IDL.Text, OrderStatus],
        [OrderStatus],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };