/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface RestorationStep {
    completed: boolean;
    description: string;
    timestamp: Time;
}
export interface FormData {
    name: string;
    email: string;
    message: string;
}
export interface Ticket {
    completed: boolean;
    formData: FormData;
    category: string;
}
export interface Order {
    customerName: string;
    status: OrderStatus;
    trackingNumber: string;
    numberOfCards: bigint;
    timestamp: Time;
    cleaningType: CleaningType;
    customerEmail: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface TrackingStateView {
    shipped: boolean;
    trackingCode: string;
    arrived: boolean;
    restorationLevel: string;
    steps: Array<RestorationStep>;
    shippingTimestamp?: Time;
}
export enum CleaningType {
    maxPotion = "maxPotion",
    superPotion = "superPotion",
    hyperPotion = "hyperPotion"
}
export enum OrderStatus {
    shipped = "shipped",
    cleaningComplete = "cleaningComplete",
    inspectionComplete = "inspectionComplete",
    finalTouches = "finalTouches",
    inPress = "inPress",
    packageReceived = "packageReceived",
    delivered = "delivered",
    processing = "processing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminId(newAdmin: Principal): Promise<void>;
    addCategories(email: string, catArray: Array<string>): Promise<void>;
    addCategory(email: string, category: string): Promise<void>;
    addRestorationStep(trackingCode: string, description: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkTrackingNumberStatus(trackingNumber: string): Promise<OrderStatus>;
    completeRestorationStep(trackingCode: string, index: bigint): Promise<void>;
    createOrder(trackingNumber: string, customerName: string, customerEmail: string, numberOfCards: bigint, cleaningType: CleaningType): Promise<OrderStatus>;
    createTrackingState(trackingCode: string, restorationLevel: string): Promise<void>;
    examineTrackingNumbers(): Promise<Array<[string, OrderStatus]>>;
    getAdminIds(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInitializationStatus(): Promise<{
        callerRole: string;
        isInitialized: boolean;
        callerIsAdmin: boolean;
    }>;
    getTrackingNumbers(): Promise<Array<[string, OrderStatus]>>;
    getTrackingState(trackingCode: string): Promise<TrackingStateView | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isTicketCompleted(email: string): Promise<boolean>;
    listAllOrders(): Promise<Array<[string, Order]>>;
    listAllTickets(): Promise<Array<[string, Ticket]>>;
    markPackageArrived(trackingCode: string): Promise<void>;
    markShipped(trackingCode: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContactForm(name: string, email: string, message: string): Promise<void>;
    updateTicketStatus(email: string, completed: boolean): Promise<void>;
    updateTrackingNumberStatus(trackingNumber: string, newStatus: OrderStatus): Promise<OrderStatus>;
}
import type { CleaningType as _CleaningType, Order as _Order, OrderStatus as _OrderStatus, RestorationStep as _RestorationStep, Time as _Time, TrackingStateView as _TrackingStateView, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminId(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminId(arg0);
            return result;
        }
    }
    async addCategories(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategories(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategories(arg0, arg1);
            return result;
        }
    }
    async addCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1);
            return result;
        }
    }
    async addRestorationStep(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRestorationStep(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRestorationStep(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkTrackingNumberStatus(arg0: string): Promise<OrderStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkTrackingNumberStatus(arg0);
                return from_candid_OrderStatus_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkTrackingNumberStatus(arg0);
            return from_candid_OrderStatus_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeRestorationStep(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeRestorationStep(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeRestorationStep(arg0, arg1);
            return result;
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: CleaningType): Promise<OrderStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, to_candid_CleaningType_n5(this._uploadFile, this._downloadFile, arg4));
                return from_candid_OrderStatus_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, to_candid_CleaningType_n5(this._uploadFile, this._downloadFile, arg4));
            return from_candid_OrderStatus_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTrackingState(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrackingState(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrackingState(arg0, arg1);
            return result;
        }
    }
    async examineTrackingNumbers(): Promise<Array<[string, OrderStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.examineTrackingNumbers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.examineTrackingNumbers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminIds(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminIds();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInitializationStatus(): Promise<{
        callerRole: string;
        isInitialized: boolean;
        callerIsAdmin: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInitializationStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInitializationStatus();
            return result;
        }
    }
    async getTrackingNumbers(): Promise<Array<[string, OrderStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackingNumbers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackingNumbers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrackingState(arg0: string): Promise<TrackingStateView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackingState(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackingState(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isTicketCompleted(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTicketCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTicketCompleted(arg0);
            return result;
        }
    }
    async listAllOrders(): Promise<Array<[string, Order]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllOrders();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllOrders();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllTickets(): Promise<Array<[string, Ticket]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllTickets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllTickets();
            return result;
        }
    }
    async markPackageArrived(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPackageArrived(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPackageArrived(arg0);
            return result;
        }
    }
    async markShipped(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markShipped(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markShipped(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTicketStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicketStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicketStatus(arg0, arg1);
            return result;
        }
    }
    async updateTrackingNumberStatus(arg0: string, arg1: OrderStatus): Promise<OrderStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrackingNumberStatus(arg0, to_candid_OrderStatus_n22(this._uploadFile, this._downloadFile, arg1));
                return from_candid_OrderStatus_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrackingNumberStatus(arg0, to_candid_OrderStatus_n22(this._uploadFile, this._downloadFile, arg1));
            return from_candid_OrderStatus_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CleaningType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CleaningType): CleaningType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TrackingStateView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackingStateView): TrackingStateView {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrackingStateView]): TrackingStateView | null {
    return value.length === 0 ? null : from_candid_TrackingStateView_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: boolean;
    trackingCode: string;
    arrived: boolean;
    restorationLevel: string;
    steps: Array<_RestorationStep>;
    shippingTimestamp: [] | [_Time];
}): {
    shipped: boolean;
    trackingCode: string;
    arrived: boolean;
    restorationLevel: string;
    steps: Array<RestorationStep>;
    shippingTimestamp?: Time;
} {
    return {
        shipped: value.shipped,
        trackingCode: value.trackingCode,
        arrived: value.arrived,
        restorationLevel: value.restorationLevel,
        steps: value.steps,
        shippingTimestamp: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.shippingTimestamp))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _OrderStatus;
    trackingNumber: string;
    numberOfCards: bigint;
    timestamp: _Time;
    cleaningType: _CleaningType;
    customerEmail: string;
}): {
    customerName: string;
    status: OrderStatus;
    trackingNumber: string;
    numberOfCards: bigint;
    timestamp: Time;
    cleaningType: CleaningType;
    customerEmail: string;
} {
    return {
        customerName: value.customerName,
        status: from_candid_OrderStatus_n3(_uploadFile, _downloadFile, value.status),
        trackingNumber: value.trackingNumber,
        numberOfCards: value.numberOfCards,
        timestamp: value.timestamp,
        cleaningType: from_candid_CleaningType_n20(_uploadFile, _downloadFile, value.cleaningType),
        customerEmail: value.customerEmail
    };
}
function from_candid_tuple_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Order]): [string, Order] {
    return [
        value[0],
        from_candid_Order_n18(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _OrderStatus]): [string, OrderStatus] {
    return [
        value[0],
        from_candid_OrderStatus_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxPotion: null;
} | {
    superPotion: null;
} | {
    hyperPotion: null;
}): CleaningType {
    return "maxPotion" in value ? CleaningType.maxPotion : "superPotion" in value ? CleaningType.superPotion : "hyperPotion" in value ? CleaningType.hyperPotion : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cleaningComplete: null;
} | {
    inspectionComplete: null;
} | {
    finalTouches: null;
} | {
    inPress: null;
} | {
    packageReceived: null;
} | {
    delivered: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cleaningComplete" in value ? OrderStatus.cleaningComplete : "inspectionComplete" in value ? OrderStatus.inspectionComplete : "finalTouches" in value ? OrderStatus.finalTouches : "inPress" in value ? OrderStatus.inPress : "packageReceived" in value ? OrderStatus.packageReceived : "delivered" in value ? OrderStatus.delivered : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Order]>): Array<[string, Order]> {
    return value.map((x)=>from_candid_tuple_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _OrderStatus]>): Array<[string, OrderStatus]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CleaningType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CleaningType): _CleaningType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cleaningComplete: null;
} | {
    inspectionComplete: null;
} | {
    finalTouches: null;
} | {
    inPress: null;
} | {
    packageReceived: null;
} | {
    delivered: null;
} | {
    processing: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cleaningComplete ? {
        cleaningComplete: null
    } : value == OrderStatus.inspectionComplete ? {
        inspectionComplete: null
    } : value == OrderStatus.finalTouches ? {
        finalTouches: null
    } : value == OrderStatus.inPress ? {
        inPress: null
    } : value == OrderStatus.packageReceived ? {
        packageReceived: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CleaningType): {
    maxPotion: null;
} | {
    superPotion: null;
} | {
    hyperPotion: null;
} {
    return value == CleaningType.maxPotion ? {
        maxPotion: null
    } : value == CleaningType.superPotion ? {
        superPotion: null
    } : value == CleaningType.hyperPotion ? {
        hyperPotion: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
